### ISSUE TITLE
Add an item/trinket that automatically uncompresses blocks

### ISSUE THREAD

**Issue by sayore** [Librv/Compressor#4]
For bigger Builds it would be really nice to have a trinket to uncompress the Blocks to be able to more quickly place them. 
Basically if you have less than 2 Stacks to fill the Blocks up with new uncompressed ones by auto uncompressing them.
Maybe even having a small GUI for it to set the amount of minimum uncompressed Blocks in the inventory?

**Comment by Librv** [comment]
Two ideas come to mind: 

- From what you said, a standalone item that the user keeps in their inventory and that converts the compressed blocks to the desired variant after a certain threshold.
I would also like to add to this trinket (or make a separate one) the ability to compress automatically the selected resource (e.g. cobblestone) into its compressed variants.    

- Something similar to a /dank/null, so a portable storage where you can insert your compressed blocks and select whichever compressed variant to place and convert to.

These option would require to either:
- add even more dependencies to Compressor
- create a standalone mod with just the trinkets (which would then have to be compatible with other compressing/uncompressing mods/recipes) and the required APIs

This can be done, but unfortunately not in the near future, since I'm currently busy IRL and with work on Chassis (config visualization and general improvements).

Feel free to add any other details/suggestions you feel are missing and thanks for the suggestion!

**Comment by Librv** [comment]
Out of scope
